l_korean:
 house_traditions_settings_decision:0 "가문 전통 모드 설정"
 house_traditions_settings_decision_tooltip:0 "가문 전통 모드 설정을 구성하기 위한 메뉴를 엽니다."
 house_traditions_settings_decision_desc:0 "가문 전통 모드 설정을 구성하기 위한 메뉴를 엽니다."
 house_traditions_settings_effect_1:0 "현재, 서로 다른 집안 간의 '결혼 적합성' 계산을 전환하는 옵션만 있습니다."
 house_traditions_settings_decision_confirm:0 "메뉴 열기"

 house_trad_settings.0001.t:0 "가문 전통 모드 설정"
 house_trad_settings.0001.desc:0 "이 메뉴는 가문 전통 모드의 설정 모음입니다.  현재는 서로 다른 집안 간의 '결혼 적합성' 계산을 전환하는 옵션만 있으며, 이는 '배우자 찾기' 도구를 사용할 때 일부 플레이어에게 일관되게 성능 문제를 일으키고 있습니다.  이 기능은 일반적으로 양립할 수 없는 집안에 대해 중요하지만 전면적인 금지 제한을 부과하기 위한 것은 아닙니다. 예를 들어 정직한 집안은 간교함을 평가하는 집안의 결혼 제안을 받아들이지 않는 경향이 있을 수 있습니다.  옵션을 끄면 대부분의 경우 AI가 명성만 보고 그 매우 무작위인 바닐라 결혼 상태로 돌아갑니다.  '배우자 찾기' 옵션이 게임을 즐기는 데 방해가 되는 경우에만 끄십시오.\n\n설정에 아주 만족하고, 절대 마음이 변하지 않을거라고 100% 확신하는 경우, 마지막 옵션을 선택하여 가문 전통 모드 설정 메뉴를 게임에서 영구적으로 숨겨겨서 더 이상 디시전 메뉴 공간을 차지하지 않도록 할 수 있습니다."
 
 house_trad_settings.0001.on_desc:0 "현재 결혼 적합성 #P 켜짐#!."
 house_trad_settings.0001.off_desc:0 "현재 결혼 적합성 #P 꺼짐#!."

 house_trad_settings.0001.on:0 "결혼 적합성 활성화"
 house_trad_settings.0001.off:0 "결혼 적합성 비활성화"
 house_trad_settings.0001.hide:0 "이 메뉴를 영구적으로 숨기기"
 house_trad_settings.0001.cancel:0 "변경 없이 메뉴 닫기"